/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wzzn_myrenzheng_Taiplayer */

#ifndef _Included_com_wzzn_myrenzheng_Taiplayer
#define _Included_com_wzzn_myrenzheng_Taiplayer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wzzn_myrenzheng_Taiplayer
 * Method:    ffmpegRecorder
 * Signature: (Ljava/lang/String;IIII)I
 */
JNIEXPORT jint JNICALL Java_com_wzzn_myrenzheng_Taiplayer_ffmpegGrabber
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_wzzn_myrenzheng_Taiplayer
 * Method:    getAudio
 * Signature: ([BJ)I
 */
JNIEXPORT jbyteArray JNICALL Java_com_wzzn_myrenzheng_Taiplayer_getAudio
  (JNIEnv *, jobject);

/*
 * Class:     com_wzzn_myrenzheng_Taiplayer
 * Method:    release
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wzzn_myrenzheng_Taiplayer_release
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
