/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wzzn_myrenzheng_Taimedia */

#ifndef _Included_com_wzzn_myrenzheng_Taimedia
#define _Included_com_wzzn_myrenzheng_Taimedia
#ifdef __cplusplus
extern "C" {
#endif



JNIEXPORT jint JNICALL Java_com_wzzn_myrenzheng_Taimedia_ffmpegGetavcodecversion
  (JNIEnv *, jobject);
JNIEXPORT jint JNICALL Java_com_wzzn_myrenzheng_Taimedia_release(JNIEnv *, jobject);
JNIEXPORT jint JNICALL Java_com_wzzn_myrenzheng_Taimedia_recordVideo
  (JNIEnv *, jobject, jbyteArray,jint,jint,jlong);
JNIEXPORT jint JNICALL Java_com_wzzn_myrenzheng_Taimedia_recordAudio
  (JNIEnv *, jobject, jbyteArray,jlong);
JNIEXPORT jint JNICALL Java_com_wzzn_myrenzheng_Taimedia_ffmpegRecorder
  (JNIEnv *, jobject, jstring,jint, jint,jint,jint);
#ifdef __cplusplus
}
#endif
#endif
